### ISSUE TITLE
solar_radiation_on_surface2 Function Not Working Properly!

### ISSUE THREAD

**Issue by junwoo091400** [ethz-asl/fw_conceptual_design#3]
I was debugging the 'AirplaneDesign.m' part.
When inside 'performanceEvaluator',  it tries to find SunRise Time and so on. So it uses
"solar_radiation_on_surface2 " function to get 'irr_vec' in return.

But I noticed that the program outputted the SunRiseTime as "48800[s]", which is over 1PM.
So I thought that was a problem. I checked each variables and they were fine.
I did 2 tests to explain the problem specifically.

1. **Flat on Ground, 6AM, June 21st, Latitude 35.8°, Longitude 128°, Altitude 535[m], Albedo 0.12** //
Result :  0         0         0         0         0         0    1.9794   -2.4607    1.9794

2. **Flat on Ground, 1.5PM, June 21st, Latitude 35.8°, Longitude 128°, Altitude 535[m], Albedo 0.12** //
Result : 0.2582    0.0175    0.2408    0.2582    0.0175    0.2408    1.5611    2.0038    1.5611

I checked every time between them. 1PM is when irr_vect(1) became 'positive' for the first time.

ANY Ideas why this is happening ???

**Comment by junwoo091400** [comment]
![image](https://user-images.githubusercontent.com/23277211/30239478-9b34722e-9598-11e7-912a-496d2cb71b97.png)

I think I got where this problem is coming from. This calculator ouputs 'GREENWICH' Irradiance. So for Longitude of 128°, Irradiation was highest at 8:30 PM (When Greenwich is 12 AM) w/ value of 977.27[W/m^2].

So thing to look at would be 'what time' it is, like it should be using Japan's time inside the program & Why it calculates Greenwich Time ... :)

I currently have to go away for School's Self Studying Time, so I will probably come back tomorrow morning and figure out the problem...

**Comment by philipoe** [comment]
@junwoo091400 Is this already addressed in your new PR https://github.com/ethz-asl/fw_conceptual_design/pull/2 ? If so, then I will have a look at this PR later on, otherwise I'd wait until this is integrated and then check it.

**Comment by junwoo091400** [comment]
@philipoe  Oh Yeah, it was fixed at https://github.com/ethz-asl/fw_conceptual_design/pull/2/commits/a7eaec43a91601924a0f7d47cf48539d599e53f0
